# Generated by Django 4.2.2 on 2023-08-16 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0004_alter_video_miniature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('State', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('IdVideoFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
    ]
