# Generated by Django 4.2.2 on 2023-08-16 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationQuestions',
            fields=[
                ('IdColaboration', models.AutoField(primary_key=True, serialize=False)),
                ('QuestionOne', models.CharField(max_length=50)),
                ('QuestionTwo', models.CharField(max_length=50)),
                ('QuestionThree', models.CharField(max_length=50)),
                ('QuestionFour', models.CharField(max_length=50)),
                ('QuestionFive', models.CharField(max_length=50)),
                ('State', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('IdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
