# Generated by Django 4.2.4 on 2023-12-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollaborationQuestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationquestions',
            name='QuestionFive',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='collaborationquestions',
            name='QuestionFour',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='collaborationquestions',
            name='QuestionOne',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='collaborationquestions',
            name='QuestionThree',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='collaborationquestions',
            name='QuestionTwo',
            field=models.CharField(max_length=240),
        ),
    ]
