# Generated by Django 4.2.4 on 2023-08-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_create_date_user_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='is_active',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='state',
        ),
    ]
