# Generated by Django 4.2.4 on 2023-08-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_active_role_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idnumber',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
