# Generated by Django 4.2.4 on 2023-08-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='idnumber',
            new_name='username',
        ),
    ]
