# Generated by Django 4.2.4 on 2023-08-29 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='idnumber',
        ),
    ]
