# Generated by Django 4.2.4 on 2023-08-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_options_rename_username_user_idnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='idnumber',
            new_name='username',
        ),
    ]
