# Generated by Django 4.2.4 on 2023-10-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='https://www.sena.edu.co/Style%20Library/alayout/images/logoSena.png', upload_to=''),
        ),
    ]
