# Generated by Django 4.2.4 on 2023-12-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_is_active_user_is_staff_alter_user_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inforpersonal',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
