# Generated by Django 4.2.4 on 2023-08-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='miniature',
            field=models.ImageField(upload_to='miniatures/'),
        ),
    ]
