# Generated by Django 4.2.4 on 2023-11-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_miniature'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
