# Generated by Django 4.2.2 on 2023-08-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelty',
            name='State',
            field=models.BooleanField(default=True),
        ),
    ]
